# This is the workflow name (optional but good)
name: Daily Commit Action

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # --- THIS IS THE FIX ---
      # The email is now in the step's name, as required by your task.
      - name: Configure Git User 23f200318@ds.study.iitm.ac.in
        run: |
          git config user.name "Daily Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          
      - name: Create a commit
        run: |
          echo "Automated run on $(date)" > daily-run.log
          git add daily-run.log
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Automated daily commit"
          fi
          
      - name: Push the commit
        run: |
          git push
